sample_name: c_ll_vl_0114
fastq_id: 'H2TJNDSXY_1_142UDI-idt-UMI H2TJNDSXY_2_142UDI-idt-UMI H2TJNDSXY_3_142UDI-idt-UMI H2TJNDSXY_4_142UDI-idt-UMI H522NDSXY_1_142UDI-idt-UMI H522NDSXY_2_142UDI-idt-UMI H522NDSXY_3_142UDI-idt-UMI H522NDSXY_4_142UDI-idt-UMI'
fastq_r1: 'H2TJNDSXY_1_142UDI-idt-UMI_1.fastp.fastq.gz H2TJNDSXY_2_142UDI-idt-UMI_1.fastp.fastq.gz H2TJNDSXY_3_142UDI-idt-UMI_1.fastp.fastq.gz H2TJNDSXY_4_142UDI-idt-UMI_1.fastp.fastq.gz H522NDSXY_1_142UDI-idt-UMI_1.fastp.fastq.gz H522NDSXY_2_142UDI-idt-UMI_1.fastp.fastq.gz H522NDSXY_3_142UDI-idt-UMI_1.fastp.fastq.gz H522NDSXY_4_142UDI-idt-UMI_1.fastp.fastq.gz'
fastq_r2: 'H2TJNDSXY_1_142UDI-idt-UMI_2.fastp.fastq.gz H2TJNDSXY_2_142UDI-idt-UMI_2.fastp.fastq.gz H2TJNDSXY_3_142UDI-idt-UMI_2.fastp.fastq.gz H2TJNDSXY_4_142UDI-idt-UMI_2.fastp.fastq.gz H522NDSXY_1_142UDI-idt-UMI_2.fastp.fastq.gz H522NDSXY_2_142UDI-idt-UMI_2.fastp.fastq.gz H522NDSXY_3_142UDI-idt-UMI_2.fastp.fastq.gz H522NDSXY_4_142UDI-idt-UMI_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_24/20200405/FASTQ/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_rufus_mLynRuf2.2/mLynRuf2.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynRuf2.2_ref_bams
threads: 20
alignment_name: mLynRuf_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'
