sample_name: c_ll_ur_0200
fastq_id: 'CBCA6ANXX_7_176nfDI'
fastq_r1: 'CBCA6ANXX_7_176nfDI_1.fastp.fastq.gz'
fastq_r2: 'CBCA6ANXX_7_176nfDI_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_18/20170828/FASTQ/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_rufus_mLynRuf2.2/mLynRuf2.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynRuf2.2_ref_bams
threads: 20
alignment_name: mLynRuf_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'
