sample_name: c_ll_ca_0247
fastq_id: 'HY5WLDSXX_1_226UDI-idt-UMI HY5WLDSXX_2_226UDI-idt-UMI HY5WLDSXX_3_226UDI-idt-UMI HY5WLDSXX_4_226UDI-idt-UMI'
fastq_r1: 'HY5WLDSXX_1_226UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_2_226UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_3_226UDI-idt-UMI_1.fastp.fastq.gz HY5WLDSXX_4_226UDI-idt-UMI_1.fastp.fastq.gz'
fastq_r2: 'HY5WLDSXX_1_226UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_2_226UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_3_226UDI-idt-UMI_2.fastp.fastq.gz HY5WLDSXX_4_226UDI-idt-UMI_2.fastp.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_21/FASTQ/fastp
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_rufus_mLynRuf2.2/mLynRuf2.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynRuf2.2_ref_bams
threads: 20
alignment_name: mLynRuf_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'
