sample_name: c_lp_sm_0226
fastq_id: 'C5RR4ACXX_3_5nf C5T3DACXX_1_5nf'
fastq_r1: 'C5RR4ACXX_3_5nf_1.fastq.gz C5T3DACXX_1_5nf_1.fastq.gz'
fastq_r2: 'C5RR4ACXX_3_5nf_2.fastq.gz C5T3DACXX_1_5nf_2.fastq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/LYNX_06_08
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_rufus_mLynRuf2.2/mLynRuf2.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynRuf2.2_ref_bams
threads: 20
alignment_name: mLynRuf_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'
