sample_name: c_lp_sm_0239
fastq_id: 'LP_239_EKDN230028707-1A_225THHLT3_L2'
fastq_r1: 'LP_239_EKDN230028707-1A_225THHLT3_L2_1.fastp.fq.gz'
fastq_r2: 'LP_239_EKDN230028707-1A_225THHLT3_L2_2.fastp.fq.gz'
in_fastq_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/FASTQ_files/novogene_lp_sept2023/fastp_output
reference_genome: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/reference_genomes/lynx_rufus_mLynRuf2.2/mLynRuf2.2.revcomp.scaffolds.fa
out_bam_folder: /mnt/lustre/hsm/nlsas/notape/home/csic/ebd/jgl/lynx_genome/lynx_data/mLynRuf2.2_ref_bams
threads: 20
alignment_name: mLynRuf_ref
bwa: bwa
samtools: samtools
picard: 'java -jar /opt/cesga/2020/software/Core/picard/2.25.5/picard.jar'
gatk: 'java -jar /opt/cesga/2020/software/Core/gatk/3.7-0-gcfedb67/GenomeAnalysisTK.jar'
